### PR TITLE
Fixes for import pattern

### PR DESCRIPTION
**Pull request by watermarkhu**
The current regex for the `meta.import.matlab` scope has bugs with regard to import wildcards and trailing whitespaces. The following illustration from regex101 shows the whitespaces better.

image

For the wildcard itself there already exists a nested scope `variable.language.wildcard.matlab`:

https://github.com/mathworks/MATLAB-Language-grammar/blob/33f9678cf14662f44f2687e298826feb14015265/Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage#L1783

Thus the fixes are needed in the main `meta.import.matlab` scope. 

image

### CODE REVIEW

**Comment by watermarkhu** [comment]
How this the numbering work in https://github.com/mathworks/MATLAB-Language-grammar/tree/master/test?

**Comment by watermarkhu** [comment]
Do you reckon this is a test that belong in the `snap` directory?

**Comment by dklilley** [comment]
I think it would make more sense to be a standalone test under the `test/` directory. I believe the snapshot tests are meant to capture much more broad tokenization, rather than specific behaviors, to prevent a change from breaking some core functionality.

Instead, I think it would be better to create a focused test which covers the cases from your above regex101 screenshots.

I believe the number preceding the test (i.e. `t##TestPoint`) should correspond to the issue being fixed. If there is no issue for this bug, you can use the number of this pull request (51).

**Comment by nothans** [comment]
Thanks for the contribution. Can you contact me to get a CLA signed? Thank you!

**Comment by nothans** [comment]
The CLA has been signed. Feel free to evaluate the PR and determine if you are going to merge. Thanks!

**Review by dklilley — APPROVED** [review]

**Comment by dklilley** [comment]
Thank you for making this fix @watermarkhu!

**Pull request merged**
