### PR TITLE
Inline improvements for command syntax

### PR DESCRIPTION
**Pull request by 4086606**
Adds semicolon and comment support for command-syntax calls.

### CODE REVIEW

**Comment by 4086606** [comment]
- [ ] Needs to include the `"#builtin_keywords"` rule instead of the `entity.name.function` hack.
- [ ] Tests need updating.

**Comment by 4086606** [comment]
@rlivings39 why is function support hacked into [`vscode-matlab`](https://github.com/Gimly/vscode-matlab) and [`language-matlab-octave`](https://github.com/thedavidprice/language-matlab-octave)? Could I bake it into this repo and sync with [reference list](https://mathworks.com/help/matlab/referencelist.html?type=function)?

**Comment by gauravsavadi** [comment]
@4086606 The reason for not including functions is the cost of keeping the list current every release. Every release, MATLAB introduces new functions, and is it not cost-effective to keep this list current.

**Comment by 4086606** [comment]
What if I put work towards this? I already amassed ~1400 missing builtin functions and assigned appropriate token names to 200. I'm sure after I'm done that a simple JS script can compare the old file with the reference list

**Comment by 4086606** [comment]
- I have adjusted the command word to `variable.function.command` and permitted injection of other grammar rules into that token. This should cover all syntax use cases and allow extensions like `vscode-matlab` to override that highlight as normal.
- I have also enabled injection of shell token highlighting into shell escapes. Thought these two features go great in one PR :)
- The package version was bumped as well to 1.1.0 - I assume the shell highlighting addition is a major change.

**Comment by nothans** [comment]
Can you contact me to have the CLA signed? Thanks for the pull request.

**Pull request merged**
