### PR TITLE
fixed attribute parsing in properties methods and events

### PR DESCRIPTION
**Pull request by apozharski**
This extends the work in #88 to also improve parsing of `property`, `events`, and `methods` blocks.

WIP until tests are updated.

### CODE REVIEW

**Comment by dklilley** [comment]
Hi @apozharski - I wanted to check back to see if there are any plans for this PR? If not, I will close this PR.
Thanks!

**Comment by apozharski** [comment]
Ah, my apologies, I got very busy and this fell off the back of the TODO list. Thanks for the reminder. Let me take a look this week at how close this was to something that could be merged, which I presume at least will involve getting tests in working order.

**Comment by dklilley** [comment]
No worries! Thank you!

**Review by dklilley — APPROVED** [review]

**Comment by dklilley** [comment]
These changes look good to me! I copied this over into the MATLAB extension for VS Code and quickly verified that the specific cases (#92 and #95) look god!

**Pull request merged**
