### PR TITLE
simplify read/write operation regex

### PR DESCRIPTION
**Pull request by watermarkhu**
The removed lines were probably copied from 
https://github.com/mathworks/MATLAB-Language-grammar/blob/4f1c0c8e8eac1494ee9c2bac18605aca08b08806/Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage#L2866

The negative lookahead on `[a-zA-Z0-9_]` does nothing due to the `[a-zA-Z0-9_]*` just before.

### CODE REVIEW

**Comment by dklilley** [comment]
Trying this out on regex101, it appears that there is a difference in behavior. The original property regex matches `asd` in `foo.asd`, but does not match it in `foo.asd(`. However, the new regex matches `as` in `foo.asd(`.

Can you confirm?

**Comment by watermarkhu** [comment]
This seems indeed to be the case. I'll add a test to this PR instead.

**Comment by watermarkhu** [comment]
Hi Duncan,
The original edit was invalid. But there also wasn't a test to check for the behavior. So the edit is disregarded but a test has been added.

**Review by dklilley — APPROVED** [review]

**Comment by dklilley** [comment]
Makes sense, thank you!

**Pull request merged**
